project_id = "xmguipmetciwvzeyxugu"

[functions.trial-signup]
verify_jwt = false

[functions.user-management]
verify_jwt = false

[functions.ai-product-import]
verify_jwt = false

[functions.clear-demo-data]
verify_jwt = false

[functions.send-offerte-email]
verify_jwt = false

[functions.ai-data-import]
verify_jwt = false

[functions.widget-submit]
verify_jwt = false

[functions.ai-lead-signals]
verify_jwt = false

[functions.google-user-provision]
verify_jwt = false

[functions.ai-verify-product-specs]
verify_jwt = false

[functions.ai-offerte-intro]
verify_jwt = false

[functions.offerte-accept]
verify_jwt = false

[functions.planning-ical-feed]
verify_jwt = false

[functions.offerte-public-view]
verify_jwt = false

[functions.ai-parse-datasheet]
verify_jwt = false

[functions.ai-feedback-categorize]
verify_jwt = false

[functions.solar-building-insights]
verify_jwt = false

[functions.ai-offerte-feedback-analyse]
verify_jwt = false
