// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (of VITE_SUPABASE_URL) is vereist");
  return url;
}
function supabasePublishableKey() {
  const key = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY",
    "SUPABASE_ANON_KEY",
    "VITE_SUPABASE_ANON_KEY"
  ]);
  if (!key) throw new Error("SUPABASE_PUBLISHABLE_KEY (of SUPABASE_ANON_KEY) is vereist");
  return key;
}
function supabaseForUser(ctx) {
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/whoami.ts
var whoami_default = defineTool({
  name: "whoami",
  title: "Wie ben ik",
  description: "Geeft het profiel van de ingelogde gebruiker terug: naam, e-mail, rol en organisatie.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Niet ingelogd" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("users").select("id, voornaam, achternaam, email, rol, partner_id, status").eq("id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? { id: ctx.getUserId() }) }],
      structuredContent: { profiel: data }
    };
  }
});

// src/lib/mcp/tools/list-leads.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z } from "npm:zod@3.25.76";
var list_leads_default = defineTool2({
  name: "list_leads",
  title: "Leads zoeken",
  description: "Zoekt leads waar de ingelogde gebruiker toegang toe heeft, optioneel gefilterd op status of zoekterm (naam, bedrijf, e-mail, plaats).",
  inputSchema: {
    zoekterm: z.string().trim().min(1).optional().describe("Zoekt in naam, bedrijfsnaam, e-mail en plaats."),
    status: z.string().trim().min(1).optional().describe("Filter op lead_status, bijv. 'nieuw' of 'gekwalificeerd'."),
    limiet: z.number().int().min(1).max(50).default(20).describe("Maximaal aantal leads.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ zoekterm, status, limiet }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Niet ingelogd" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("leads").select("id, voornaam, achternaam, bedrijfsnaam, email, telefoon, plaats, lead_status, bron, created_at").order("created_at", { ascending: false }).limit(limiet ?? 20);
    if (status) query = query.eq("lead_status", status);
    if (zoekterm) {
      const term = `%${zoekterm}%`;
      query = query.or(
        `voornaam.ilike.${term},achternaam.ilike.${term},bedrijfsnaam.ilike.${term},email.ilike.${term},plaats.ilike.${term}`
      );
    }
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { leads: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-lead.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z2 } from "npm:zod@3.25.76";
var get_lead_default = defineTool3({
  name: "get_lead",
  title: "Lead ophalen",
  description: "Haalt \xE9\xE9n lead op met de laatste notities en bijbehorende offertes.",
  inputSchema: { lead_id: z2.string().uuid().describe("Het id van de lead.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ lead_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Niet ingelogd" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: lead, error } = await supabase.from("leads").select("*").eq("id", lead_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!lead) return { content: [{ type: "text", text: "Lead niet gevonden" }], isError: true };
    const [{ data: notities }, { data: offertes }] = await Promise.all([
      supabase.from("lead_notities").select("id, titel, inhoud, intern, created_at").eq("lead_id", lead_id).order("created_at", { ascending: false }).limit(10),
      supabase.from("offertes").select("id, offertenummer, status, totaal_bedrag, created_at").eq("lead_id", lead_id).order("created_at", { ascending: false }).limit(10)
    ]);
    const resultaat = { lead, notities: notities ?? [], offertes: offertes ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(resultaat) }],
      structuredContent: resultaat
    };
  }
});

// src/lib/mcp/tools/list-offertes.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z3 } from "npm:zod@3.25.76";
var list_offertes_default = defineTool4({
  name: "list_offertes",
  title: "Offertes zoeken",
  description: "Toont offertes waar de ingelogde gebruiker toegang toe heeft, optioneel gefilterd op status of klantnaam.",
  inputSchema: {
    status: z3.string().trim().min(1).optional().describe("Filter op status, bijv. 'concept', 'verzonden' of 'geaccepteerd'."),
    klant: z3.string().trim().min(1).optional().describe("Zoekt in klantnaam en offertenummer."),
    limiet: z3.number().int().min(1).max(50).default(20).describe("Maximaal aantal offertes.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, klant, limiet }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Niet ingelogd" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("offertes").select("id, offertenummer, klant_naam, klant_plaats, status, totaal_bedrag, geldig_tot, created_at").order("created_at", { ascending: false }).limit(limiet ?? 20);
    if (status) query = query.eq("status", status);
    if (klant) {
      const term = `%${klant}%`;
      query = query.or(`klant_naam.ilike.${term},offertenummer.ilike.${term}`);
    }
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { offertes: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-installaties.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z4 } from "npm:zod@3.25.76";
var list_installaties_default = defineTool5({
  name: "list_installaties",
  title: "Installaties plannen bekijken",
  description: "Toont geplande installaties, optioneel gefilterd op status en startdatum-bereik.",
  inputSchema: {
    status: z4.string().trim().min(1).optional().describe("Filter op status, bijv. 'gepland' of 'afgerond'."),
    vanaf: z4.string().date().optional().describe("Startdatum vanaf (YYYY-MM-DD)."),
    tot: z4.string().date().optional().describe("Startdatum tot en met (YYYY-MM-DD)."),
    limiet: z4.number().int().min(1).max(50).default(20).describe("Maximaal aantal installaties.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, vanaf, tot, limiet }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Niet ingelogd" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("installaties").select(
      "id, installatienummer, klant_adres, klant_plaats, status, geplande_startdatum, geplande_einddatum, werkomschrijving"
    ).order("geplande_startdatum", { ascending: true }).limit(limiet ?? 20);
    if (status) query = query.eq("status", status);
    if (vanaf) query = query.gte("geplande_startdatum", vanaf);
    if (tot) query = query.lte("geplande_startdatum", tot);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { installaties: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-lead-notitie.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z5 } from "npm:zod@3.25.76";
var create_lead_notitie_default = defineTool6({
  name: "create_lead_notitie",
  title: "Notitie bij lead plaatsen",
  description: "Voegt een notitie toe aan een lead namens de ingelogde gebruiker.",
  inputSchema: {
    lead_id: z5.string().uuid().describe("Het id van de lead."),
    inhoud: z5.string().trim().min(1).max(5e3).describe("De tekst van de notitie."),
    titel: z5.string().trim().min(1).max(200).optional().describe("Optionele titel."),
    intern: z5.boolean().default(true).describe("Interne notitie (niet zichtbaar voor de klant).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ lead_id, inhoud, titel, intern }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Niet ingelogd" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: lead, error: leadError } = await supabase.from("leads").select("id, partner_id").eq("id", lead_id).maybeSingle();
    if (leadError) return { content: [{ type: "text", text: leadError.message }], isError: true };
    if (!lead) return { content: [{ type: "text", text: "Lead niet gevonden" }], isError: true };
    const { data, error } = await supabase.from("lead_notities").insert({
      lead_id,
      partner_id: lead.partner_id,
      user_id: ctx.getUserId(),
      inhoud,
      titel: titel ?? null,
      intern: intern ?? true
    }).select("id, titel, inhoud, intern, created_at").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { notitie: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "xmguipmetciwvzeyxugu";
var mcp_default = defineMcp({
  name: "mijnhuis-nu-backend",
  title: "Mijnhuis.nu (backend)",
  version: "0.1.0",
  instructions: "Tools voor Mijnhuis.nu. Gebruik `whoami` voor het eigen profiel, `list_leads` en `get_lead` voor leads, `list_offertes` voor offertes, `list_installaties` voor de installatieplanning en `create_lead_notitie` om een notitie bij een lead te plaatsen. Alle data is beperkt tot wat de ingelogde gebruiker mag zien.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    whoami_default,
    list_leads_default,
    get_lead_default,
    list_offertes_default,
    list_installaties_default,
    create_lead_notitie_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
